[package]
name = "rrt"
version = "0.1.0"
authors = ["Michael Maclean <michael@no-surprises.co.uk>"]

[dependencies]
num = "0.1.36"
docopt = "0.6.86"
rustc-serialize = "0.3.22"

serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8" 
